#!/usr/bin/env node

// bin/pull-forms.ts
import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { resolve, dirname } from "path";
function loadEnv() {
  const env = {};
  try {
    const content = readFileSync(resolve(process.cwd(), ".env"), "utf-8");
    for (const line of content.split("\n")) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith("#")) continue;
      const eqIndex = trimmed.indexOf("=");
      if (eqIndex === -1) continue;
      const key = trimmed.slice(0, eqIndex).trim();
      let value = trimmed.slice(eqIndex + 1).trim();
      if (value.startsWith('"') && value.endsWith('"') || value.startsWith("'") && value.endsWith("'")) {
        value = value.slice(1, -1);
      }
      env[key] = value;
    }
  } catch {
  }
  return env;
}
function getConfig() {
  const env = loadEnv();
  const brainApiKey = env.BRAIN_API_KEY ?? process.env.BRAIN_API_KEY;
  const brainUrl = env.BRAIN_URL ?? process.env.BRAIN_URL;
  if (!brainApiKey) {
    console.error("Error: BRAIN_API_KEY not found in .env or environment");
    process.exit(1);
  }
  if (!brainUrl) {
    console.error("Error: BRAIN_URL not found in .env or environment");
    process.exit(1);
  }
  return { brainApiKey, brainUrl };
}
function parseArgs() {
  const args = process.argv.slice(2);
  let output = "src/generated/forms.ts";
  for (let i = 0; i < args.length; i++) {
    const nextArg = args[i + 1];
    if (args[i] === "--output" && nextArg) {
      output = nextArg;
      i++;
    }
  }
  return { output };
}
function slugToCamelCase(slug) {
  const cleaned = slug.replace(/[^a-zA-Z0-9-_]/g, "");
  const parts = cleaned.split(/[-_]+/).filter(Boolean);
  if (parts.length === 0) return "form";
  let result = "";
  const first = parts[0];
  if (/^\d/.test(first)) {
    result = "form" + first.charAt(0).toUpperCase() + first.slice(1);
  } else {
    result = first;
  }
  for (let i = 1; i < parts.length; i++) {
    const part = parts[i];
    result += part.charAt(0).toUpperCase() + part.slice(1);
  }
  return result;
}
function fieldToZodCode(field) {
  let code;
  switch (field.type) {
    case "email":
      code = field.required ? "z.string().email()" : "z.string().email().optional()";
      break;
    case "url":
      code = field.required ? "z.string().url()" : "z.string().url().optional()";
      break;
    case "number":
      code = field.required ? "z.coerce.number()" : "z.coerce.number().optional()";
      break;
    case "checkbox":
      code = field.required ? "z.boolean()" : "z.boolean().optional()";
      break;
    case "select":
      if (field.options && field.options.length > 0) {
        const opts = field.options.map((o) => `'${o.replace(/'/g, "\\'")}'`).join(", ");
        code = field.required ? `z.enum([${opts}])` : `z.enum([${opts}]).optional()`;
      } else {
        code = field.required ? "z.string().min(1)" : "z.string().optional()";
      }
      break;
    default:
      code = field.required ? "z.string().min(1)" : "z.string().optional()";
      break;
  }
  return code;
}
function generateFileContent(forms) {
  const lines = [
    "// Auto-generated by @growth-engine/sdk-server pull-forms",
    "// Run `pnpm pull-forms` to regenerate",
    `// Last updated: ${(/* @__PURE__ */ new Date()).toISOString()}`,
    "",
    "import { z } from 'zod'",
    ""
  ];
  for (const form of forms) {
    const camel = slugToCamelCase(form.slug);
    lines.push(`// --- ${form.slug} ---`);
    lines.push(`export const ${camel}Schema = z.object({`);
    for (const field of form.fields) {
      lines.push(`  ${field.name}: ${fieldToZodCode(field)},`);
    }
    lines.push("})");
    lines.push(`export type ${camel.charAt(0).toUpperCase() + camel.slice(1)}Data = z.infer<typeof ${camel}Schema>`);
    lines.push("");
  }
  if (forms.length > 0) {
    lines.push("// Form slug constants");
    lines.push("export const FormSlugs = {");
    for (const form of forms) {
      const camel = slugToCamelCase(form.slug);
      lines.push(`  ${camel}: '${form.slug}',`);
    }
    lines.push("} as const");
    lines.push("export type FormSlug = (typeof FormSlugs)[keyof typeof FormSlugs]");
    lines.push("");
  }
  return lines.join("\n");
}
async function main() {
  const { brainApiKey, brainUrl } = getConfig();
  const { output } = parseArgs();
  console.log("Fetching form definitions from Brain...");
  let response;
  try {
    response = await fetch(`${brainUrl}/api/sdk/forms/schema`, {
      headers: { "x-api-key": brainApiKey }
    });
  } catch (err) {
    console.error(`Error: Could not connect to Brain at ${brainUrl}`);
    console.error(err instanceof Error ? err.message : String(err));
    process.exit(1);
  }
  if (!response.ok) {
    const text = await response.text().catch(() => "");
    console.error(`Error: Brain returned status ${response.status}`);
    if (text) console.error(text);
    process.exit(1);
  }
  const data = await response.json();
  const { forms } = data;
  if (!forms || forms.length === 0) {
    console.error("Error: No active forms found for this tenant");
    process.exit(1);
  }
  const outputPath = resolve(process.cwd(), output);
  const content = generateFileContent(forms);
  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, content, "utf-8");
  console.log(`Generated ${forms.length} form schema(s) \u2192 ${output}`);
}
main().catch((err) => {
  console.error("Unexpected error:", err);
  process.exit(1);
});
//# sourceMappingURL=pull-forms.js.map